AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy Polymarket HFT Bot Infrastructure'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: String
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  
  InstanceType:
    Description: High-performance HFT instance type
    Type: String
    Default: c6i.large
    AllowedValues:
      - c6i.large
      - c6i.xlarge
      - c7g.large
      - c7g.xlarge
      - t3.large
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Mappings: 
  RegionMap: 
    us-east-1: 
      AMI: ami-0532be01f26a3de55  # Amazon Linux 2023 64-bit (x86_64) - Updated 2025
    us-east-2: 
      AMI: ami-05fb0b8c1424f266b
    eu-west-1: 
      AMI: ami-01dd271720c1ba44f
    ap-southeast-1:
      AMI: ami-0d07675d294f17973 # Singapore
    ap-southeast-2:
      AMI: ami-048ab8ac7e8c6533d # Sydney

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref SSHLocation

  HFTInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref HFTInstanceProfile
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      Tags: 
        - Key: Name
          Value: Polymarket-HFT-Bot
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x # Enable debug printing
          
          # Update system
          dnf update -y
          
          # Install critical tools
          dnf install -y --allowerasing git gcc openssl-devel curl amazon-cloudwatch-agent clang lld
          
          # Try to install extras
          dnf install -y --allowerasing tmux htop || echo "Extras installation failed, continuing..."

          # Install Rust (as ec2-user)
          runuser -l ec2-user -c 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
          
          # Clone repository
          cd /home/ec2-user
          runuser -l ec2-user -c 'git clone https://github.com/0xBoji/polymarket-sniper-rs.git /home/ec2-user/bot' || echo "Git clone failed"
          
          # Configure Cargo for fast linking (lld)
          mkdir -p /home/ec2-user/.cargo
          cat <<EOF > /home/ec2-user/.cargo/config.toml
          [target.x86_64-unknown-linux-gnu]
          linker = "clang"
          rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]
          EOF
          chown -R ec2-user:ec2-user /home/ec2-user/.cargo
          
          if [ -d "/home/ec2-user/bot" ]; then
              # Create .env file with placeholders
              cat <<EOF > /home/ec2-user/bot/.env
              POLYMARKET_API_KEY=YOUR_API_KEY
              POLYMARKET_SECRET=YOUR_SECRET
              POLYMARKET_PASSPHRASE=YOUR_PASSPHRASE
              POLYMARKET_HOST=https://clob.polymarket.com
              POLYGON_WS_RPC=YOUR_WS_RPC
              PAPER_TRADING=false
              MAX_POSITION_SIZE_PCT=5.0
              MAX_PORTFOLIO_EXPOSURE_PCT=50.0
              STOP_LOSS_PCT=10.0
              MIN_MARKET_VOLUME=1000.0
              MIN_LIQUIDITY=500.0
              MARKET_POLL_INTERVAL_SECS=60
              RUST_LOG=info,polymarket_hft_agent=debug
              POLYGON_PRIVATE_KEY=YOUR_PRIVATE_KEY
              CTF_CONTRACT_ADDRESS=0x4D97DCd97eC945f40cF65F87097ACe5EA0476045
              MAX_POSITION_SIZE_USD=1.0
              EOF
          
              chown ec2-user:ec2-user /home/ec2-user/bot/.env
              
              # Configuration for CloudWatch Agent
              cat <<EOF > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
              {
                "logs": {
                  "logs_collected": {
                    "files": {
                      "collect_list": [
                        {
                          "file_path": "/home/ec2-user/bot/bot.log",
                          "log_group_name": "Polymarket-HFT-Bot",
                          "log_stream_name": "{instance_id}",
                          "timestamp_format": "%Y-%m-%dT%H:%M:%S"
                        }
                      ]
                    }
                  }
                }
              }
              EOF

              # Start CloudWatch Agent
              /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
              
              # Build in background
              runuser -l ec2-user -c 'source $HOME/.cargo/env && cd /home/ec2-user/bot && cargo build --release'
          fi
          
          echo "Setup Complete."

  HFTInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: LogCleanupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:DeleteLogStream
                  - logs:DeleteLogGroup
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:Polymarket-HFT-Bot:*'

  HFTInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref HFTInstanceRole

  HFTLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: Polymarket-HFT-Bot
      RetentionInDays: 7

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref HFTInstance
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [HFTInstance, PublicIp]
  LogGroupName:
    Description: CloudWatch Log Group
    Value: Polymarket-HFT-Bot
